### ISSUE TITLE
Missing directories and files in the repo

### ISSUE THREAD

**Issue by smortaheb** [CyclotronResearchCentre/shamo-tutorials#5]
Hello, 

I am trying to run the tutorials of this repository. 
However, in the notebooks (e.g., hd_tdcs_simulation.ipynb), it refers to some JSON files in the ``` derivative``` folder that do not exist in the repository. 

How can I run these codes properly? 

thank you very much.

**Comment by MartinGrignard** [comment]
Hi :wave:,

The data in the `derivatives` directory come from previous steps.
For instance, the data required for the `hd_tdcs_simulation.ipynb` you are talking about requires the `../../derivatives/fem_from_labels/fem_from_labels.json` file, which, as shown in the name of the directory, is produced while executing the `fem_from_labels.ipynb` notebook.

Indeed, simulating electric current in shamo requires to first produce the finite element model (using any of the available methods).
In general, the workflow is the following:

1. Generate a finite element model:
    - Build the mesh
    - Define the tissues
    - Add the electrodes
2. Define the problem (EEG, tDCS...)
3. Solve the problem (i.e. run the actual simulation(s))
